server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
polar:
  greeting: Hello from local book catalog!
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/PolarBookshop
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:25432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  application.name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config.import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
management:
  endpoints:
    web:
      exposure:
        include: health,loggers,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
