apiVersion: v1
kind: ConfigMap
metadata:
  namespace: polar
  name: catalog-config
  labels:
    app: catalog-service
data:
  application.yml: |
    polar:
      greeting: Welcome to the book catalog from Kubernetes!
      test-data:
        enabled: true
    spring:
      datasource:
        url: jdbc:postgresql://polar-postgres/polardb_catalog
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://polar-keycloak/realms/PolarBookshop
